stages:
  - test
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

deploy_to_flai:
  stage: deploy
  script:
    - apk update
    - apk add openssh 
    - apk add sshpass
    - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$SERVER_ADDRESS /bin/bash <<'EOT'
    - cd ia5_teamprojekt_flai
    - sudo docker-compose down
    - sudo rm -rf backend/postgres_db/pgdata
    - git checkout .
    - git checkout main
    - git pull
    - sudo docker-compose build
    - sudo docker-compose up -d
    - EOT
    - echo "------------> Automatic deploy finished successfully!"
  only:
    - main
