POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "miriam.weber@email.com",
    "password": "supersecret"
}

###
// refresh token currently not in use
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "token": ""
}

###

// Compared to the web client side, the rest client logout works
// but it cant delete the jwt token since it´s a env variable
DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "token": ""
}