POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username": "Martin"
}

###


GET http://localhost:5000/api/exercises
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFydGluIiwiaWF0IjoxNjM5OTk4MTA4fQ.w1s5sLr8VwYTVeTnPVRCC7HjNN8w-1mk2DScrDKrj_w