PATCH http://localhost:5000/api/exercise-settings
Authorization: {{token}}
Content-Type: application/json

{
    "data": {
        "task_split": 0.7
    },
    "ids": {
        "exercise_id": "{{exercise_id}}",
        "user_id": "{{user_id}}"
    }
}