// including start_time as an attribute in exercise_session GET depending on usecase
@start_time=2021-01-31 10:45:00.595133+00

GET http://localhost:5000/api/exercise-session/?exercise_id={{exercise_id}}&&user_id={{user_id}}
Authorization: {{token}}

### 

POST http://localhost:5000/api/exercise-session/
Authorization: {{token}}
Content-Type: application/json

{
    "exercise_id": "{{exercise_id}}",
    "user_id": "{{user_id}}",
    "start_time": "{{start_time}}"
} 

### 



PATCH http://localhost:5000/api/exercise-session/
Authorization: {{token}}
Content-Type: application/json

{
    "data": {
        "session_duration": "00:45:00"
    },
    "ids": {
        "exercise_id": "{{exercise_id}}",
        "user_id": "{{user_id}}",
        "start_time": "{{start_time}}"
    }
} 

### 

DELETE http://localhost:5000/api/exercise-session/
Authorization: {{token}}
Content-Type: application/json

{
        "exercise_id": "{{exercise_id}}",
        "user_id": "{{user_id}}",
        "start_time": "{{start_time}}"
}
 