GET http://localhost:5000/api/exercise/all
Authorization: bearer
bearer: eyJhbGciOiJIUzI1NiJ9.MDc5Yzg3MjUtM2I0Ny00MzRjLWJhMWEtYWZlM2E4MTYyZGFj.X2bs0vZQyfT-asu-S_hHdwpfhzTFm2rvQmy65LzeWmU

###

GET http://localhost:5000/api/exercise/
Content-Type: application/json

{
    "id": "b86c7bf4-38c5-460a-9692-cfd08f896976",
    "user_id": "13d5bf29-8610-49ae-adc6-c41e636dfd88"
}

### 