GET http://localhost:5000/api/exercise-session/
Content-Type: application/json

{
    "exercise_id": "b86c7bf4-38c5-460a-9692-cfd08f896976",
    "user_id": "64dd868f-cda6-41c8-a574-23d1b42fa04d"
}

### 

POST http://localhost:5000/api/exercise-session/
Content-Type: application/json

{
    "exercise_id": "b86c7bf4-38c5-460a-9692-cfd08f896976",
    "user_id": "64dd868f-cda6-41c8-a574-23d1b42fa04d",
    "start_time": "2021-12-27 10:45:00.595133+00"
} 

### 

PATCH http://localhost:5000/api/exercise-session/
Content-Type: application/json

{
    "data": {
        "session_duration": "00:35:00"
    },
    "ids": {
        "exercise_id": "b86c7bf4-38c5-460a-9692-cfd08f896976",
        "user_id": "64dd868f-cda6-41c8-a574-23d1b42fa04d",
        "start_time": "2021-12-27 10:45:00.595133+00"
    }
} 

### 

DELETE http://localhost:5000/api/exercise-session/
Content-Type: application/json

{
    "exercise_id": "b86c7bf4-38c5-460a-9692-cfd08f896976",
    "user_id": "13d5bf29-8610-49ae-adc6-c41e636dfd88"
} 