GET http://localhost:5000/api/progress/?user_id={{user_id}}&&exercise_id={{exercise_id}}
Authorization: {{token}}
###

PATCH http://localhost:5000/api/progress/	
Authorization: {{token}}
Content-Type: application/json

{
    "data": {
        "progress": 300
    },
    
    "ids": 
    {
        "user_id": "{{user_id}}",
        "exercise_id": "{{exercise_id}}",
        "sign_id": "4ac39267-0ed2-450c-8406-5faeb565c822"

    }

}