GET http://localhost:5000/api/progress/?user_id={{user_id}}&&exercise_id={{exercise_id}}
Authorization: {{token}}
###


@sign_id=insert a sign_id from the GET request

PATCH http://localhost:5000/api/progress/	
Authorization: {{token}}
Content-Type: application/json

{
    "data": {
        "progress": 15
    },
    
    "ids": 
    {
        "user_id": "{{user_id}}",
        "exercise_id": "{{exercise_id}}",
        "sign_id": "{{sign_id}}"
    }

}