GET http://localhost:5000/api/accounts/e5fbc121-db91-4193-8d2d-5506a6f5ecf2

### 

POST http://localhost:5000/api/accounts
Content-Type: application/json

{
    "username": "martin",
    "password": "testmk1",
    "email": "martin4.ko@cool.de"
}

###

PATCH http://localhost:5000/api/accounts/1b4b4229-9e0a-42e1-b9b8-f28fd64a2b31	
Content-Type: application/json

{
    "username": "martinne"
}

###

DELETE http://localhost:5000/api/accounts/239d7827-39c9-49fe-9c27-892bee5c9567