@sign_recording_id=insert id from get_sign_recording view

GET http://localhost:5000/api/sign-recording/sign/?id={{sign_recording_id}}

### 


@sign_recording_for_exercise_id=insert id from get_sign_recording_for_exercise view

GET http://localhost:5000/api/sign-recording/sign/exercise/?id={{sign_recording_for_exercise_id}}
