@sign_recording_id=8c417e5d-9854-4cdb-bbeb-75d7ca290d7e

GET http://localhost:5000/api/sign-recording/sign/?id={{sign_recording_id}}

### 


@sign_recording_for_exercise_id=85695945-d0f9-46ce-85f8-3e4593393dcb

GET http://localhost:5000/api/sign-recording/sign/exercise/?id={{sign_recording_for_exercise_id}}
