GET http://localhost:5000/api/statistic/active_streak/?user_id={{user_id}}
Authorization: {{token}}

###

GET http://localhost:5000/api/statistic/longest_streak/?user_id={{user_id}}
Authorization: {{token}}

###

GET http://localhost:5000/api/statistic/exercise_completion/?user_id={{user_id}}&&exercise_id={{exercise_id}}
Authorization: {{token}}

###

GET http://localhost:5000/api/statistic/best_exercise_sign/?user_id={{user_id}}&&exercise_id={{exercise_id}}
Authorization: {{token}}

###

//use a day from get_time_learnt_by_day and user_id
GET http://localhost:5000/api/statistic/time_learnt_by_day/?user_id={{user_id}}&&day=2022-01-15
Authorization: {{token}}

###

GET http://localhost:5000/api/statistic/trends/?user_id={{user_id}}&&end_day=2022-01-17&&days=2
Authorization: {{token}}

###
