
GET http://localhost:5000/api/user/?id={{user_id}}
Authorization: {{token}}
### 

POST http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "Martin Kohnle",
    "password": "best4flai!",
    "email": "martin.kohnle@flai.de"
}

###

PATCH http://localhost:5000/api/user
Authorization: {{token}}
Content-Type: application/json

{   
    "data": 
    {
        "username": "Martin"
    },
    
    "ids": 
    {
        "id": "{{user_id}}"
    }
}

###

DELETE http://localhost:5000/api/user/?id={{user_id}}
Authorization: {{token}}