
GET http://localhost:5000/api/user/?id={{user_id}}
Authorization: {{token}}
### 

POST http://localhost:5000/api/user
Content-Type: application/json

{
    "username": "Max Mustermann",
    "password": "max4Muster!",
    "email": "max-muster@flai.de"
}

###

PATCH http://localhost:5000/api/user
Authorization: {{token}}
Content-Type: application/json

{   
    "data": 
    {
        "username": "example_name"
    },
    
    "ids": 
    {
        "id": "{{user_id}}"
    }
}

###

DELETE http://localhost:5000/api/user/?id={{user_id}}
Authorization: {{token}}